# Generated by Django 4.2.7 on 2025-09-25 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jwttoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "JWT Token",
                "verbose_name_plural": "JWT Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="jwttoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Token creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="jwttoken",
            name="expires_at",
            field=models.DateTimeField(help_text="Timestamp when the token expires"),
        ),
        migrations.AlterField(
            model_name="jwttoken",
            name="is_revoked",
            field=models.BooleanField(
                default=False, help_text="Whether the token has been manually revoked"
            ),
        ),
        migrations.AlterField(
            model_name="jwttoken",
            name="token_hash",
            field=models.CharField(
                help_text="Hashed version of the JWT token for security",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="jwttoken",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last token update timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="jwttoken",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this token",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jwt_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time when the user account was created",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="User's unique email address for authentication",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(help_text="User's first name", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(help_text="User's last name", max_length=150),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(
                blank=True, help_text="User's street address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL to user's profile picture",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="User's biography or description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                blank=True, help_text="User's city", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(
                blank=True, help_text="User's country", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Profile creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="User's date of birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="User's contact phone number",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="User's postal or zip code",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="User's state or province",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last profile update timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                help_text="User associated with this profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
