#!/bin/bash

echo "=== Getting Current PostgreSQL Connection Details ==="
echo ""
echo "Please run the following commands to get the current database connection details:"
echo ""
echo "1. Link to the PostgreSQL project:"
echo "   railway link"
echo "   (Select: Khaled Khedr's Projects -> discerning-curiosity -> production -> Postgres)"
echo ""
echo "2. Get the variables:"
echo "   railway variables"
echo ""
echo "3. Look for these specific variables:"
echo "   - RAILWAY_TCP_PROXY_DOMAIN"
echo "   - RAILWAY_TCP_PROXY_PORT"
echo "   - DATABASE_PUBLIC_URL"
echo ""
echo "The current configuration is using:"
echo "   Host: nozomi.proxy.rlwy.net"
echo "   Port: 24106"
echo ""
echo "If these have changed, we need to update the Django settings."
