# Generated by Django 4.2.7 on 2025-09-25 06:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "categories",
            "0002_rename_categories_slug_b4303a_idx_categories_slug_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="productspecification",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Cart creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                help_text="Cart owner (one cart per user)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                help_text="Related shopping cart",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Item addition timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                help_text="Product in the cart",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Quantity of the product (minimum 1)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                help_text="Customer who placed the order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_bought",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Order placement timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(help_text="Delivery address for the order"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current order status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total order amount (minimum $0.01)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last status change timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Order item creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                help_text="Related order instance",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price per unit at time of purchase",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                help_text="Product that was ordered",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Quantity ordered (minimum 1)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="seller",
            field=models.ForeignKey(
                help_text="Seller of the product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_sold",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Product category for organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Product creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="Detailed product description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Primary product image URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether product is visible and purchasable"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Product display name", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Product price (minimum $0.01)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                help_text="Vendor/seller who owns this product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_selling",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Brief product summary for listings",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Available inventory quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Alternative text for accessibility",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Image upload timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(help_text="Image URL or file path"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Whether this is the primary product image"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="Related product instance",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order for image galleries"
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Specification creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="name",
            field=models.CharField(
                help_text="Specification name (e.g., 'Color', 'Size')", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="product",
            field=models.ForeignKey(
                help_text="Related product instance",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="value",
            field=models.CharField(
                help_text="Specification value (e.g., 'Red', 'Large')", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="carts_user_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product"], name="cart_items_cart_prod_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "status"], name="orders_buyer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_created_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="order_items_order_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["seller", "created_at"], name="order_items_seller_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["product"], name="order_items_product_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "category"], name="products_active_cat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller", "is_active"], name="products_seller_act_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_price_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock_quantity"], name="products_stock_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["created_at"], name="products_created_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="prod_img_prod_primary_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "sort_order"], name="prod_img_prod_sort_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productspecification",
            index=models.Index(
                fields=["product", "name"], name="prod_specs_prod_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gt", 0)), name="products_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("stock_quantity__gte", 0)),
                name="products_stock_non_negative",
            ),
        ),
    ]
