# Generated by Django 4.2.7 on 2025-09-15 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=200, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="categories_slug_b4303a_idx"),
                    models.Index(
                        fields=["parent"], name="categories_parent__7983b2_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="categories_is_acti_aae090_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="categories_sort_or_77e69f_idx"
                    ),
                    models.Index(fields=["name"], name="categories_name_98d7d5_idx"),
                    models.Index(
                        fields=["parent", "is_active"],
                        name="categories_parent__c20446_idx",
                    ),
                ],
            },
        ),
    ]
