# Generated by Django 4.2.7 on 2025-09-25 06:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="category",
            new_name="categories_slug_idx",
            old_name="categories_slug_b4303a_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="categories_parent_idx",
            old_name="categories_parent__7983b2_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="categories_active_idx",
            old_name="categories_is_acti_aae090_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="categories_sort_idx",
            old_name="categories_sort_or_77e69f_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="categories_name_idx",
            old_name="categories_name_98d7d5_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="categories_parent_act_idx",
            old_name="categories_parent__c20446_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when category was created"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of the category", null=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this category is visible and usable"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="SEO meta description for search engines",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO page title for search engines",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Display name of the category", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category for hierarchical organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly identifier, auto-generated from name",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Display order within the same parent level (0-9999)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when category was last modified"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["sort_order", "name"], name="categories_sort_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                check=models.Q(("sort_order__gte", 0)),
                name="categories_sort_order_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("parent", "sort_order"),
                name="unique_sort_per_parent",
            ),
        ),
    ]
